### ISSUE TITLE
AR Touches to fire screenPointToRay only work on Android and not iOS WebXR Viewer

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#118] opened 2022-11-25 13:01 UTC
### Describe the bug 💬

Using touch events subscribed at 
```
    this.context.domElement.addEventListener("touchstart", e => {
        console.log("touchstart", e);
        for (let i = 0; i < e.changedTouches.length; i++) {
            const touch = e.changedTouches[i];
            const ray = this.screenPointToRay(touch.clientX, touch.clientY);
            Gizmos.DrawRay(ray.origin, ray.direction, 0xff0000, 10);
        }
    });
``` 
Those events don't seem to fire raycasts in AR on iOS in Mozilla WebXR Viewer (the touch events do fire outside of AR though on iOS), but it works fine on Android inside/outside AR using Chrome. You should be able to see the red debug rays drawn when performing touches while in AR and non AR view in the sample project

Related Discord forum post: https://discord.com/channels/717429793926283276/1044292640176345118/1044293702002163823

### Operating System 👩‍💻

iOS (mobile), Android (mobile)

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome, Mozilla XR

### Editor Version 🎲

2022.x

### Needle Exporter version

2.49.0-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "C:/Unity_Projects/NeedleWebDemos/Assets",
  "UnityVersion": "2022.1.23f1",
  "SceneName": "ARDemo",
  "ProjectPath": "Projects/ARDemo",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": false,
  "RenderPipeline": "UniversalRenderPipelineAsset (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.49.0-pre",
  "NeedleEngineVersion": "2.49.0-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 2 = 0.7 mb\r\n•\t<b>Total = 0.7 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 2 = 0.7 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.Components.WebARSessionRoot",
    "Needle.Engine.Components.TeleportTarget",
    "Needle.Engine.Components.ObjectRaycaster",
    "Needle.Engine.AdditionalData.LightShadowData",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.WebXRSync",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.AdditionalData.CameraARData",
    "Needle.Typescript.GeneratedComponents.AlignHeightToGround",
    "Needle.Typescript.GeneratedComponents.ARControls",
    "Needle.Typescript.GeneratedComponents.DragControlsEPM"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1. Open Repro project in Unity 2022.1.23f1
2. Run local server, open on iOS in Mozilla WebXR viewer
3. Try touching the screen outside of AR mode to see raycasts working, then try entering AR mode and touching to raycast
4. Do the same on Android with Chrome to see AR raycasts work fine
```

### Reproduction ♻

Repro Project:
[ARDemo-221125_uw.zip](https://github.com/needle-tools/needle-engine-support/files/10092771/ARDemo-221125_uw.zip)

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment] 2022-11-25 13:03
MozillaXR does something weird with the canvas when in AR - for example when exiting AR the canvas is not in the DOM anymore. I would suspect this issue is caused by that maybe? Can you try subscribing to the events on the document body or window instead?

**Comment by marwie** [comment] 2022-11-25 13:04
Alternatively you should also be able to use ``this.context.input.getPointer..`` methods now - would be great if you could try that too

**Comment by ROBYER1** [comment] 2022-11-25 13:11
> Alternatively you should also be able to use `this.context.input.getPointer..` methods now - would be great if you could try that too

Will those methods apply to touch and pointer inputs universally? I am off for the afternoon now but I have another issue with that same project where it won't actually build dev or prod builds due to something in the particle system in Needle Package cache which I'll report if I have time.

**Comment by marwie** [comment] 2022-11-25 17:38
The particles error should be fixed in the latest version.

Let me know when you have tested the suggested methods above and / or subbing to doc or window

**Comment by ROBYER1** [comment] 2022-11-28 15:56
I just tested subscribing the events to the window with `window.addEventListener` like below but I could only get the touchEnd events to fire while in AR in Mozilla WebXR viewer

```
    window.addEventListener("touchstart", e => {
        console.log("touchstart", e);
        for (let i = 0; i < e.changedTouches.length; i++) {
            const touch = e.changedTouches[i];
            const ray = this.screenPointToRay(touch.clientX, touch.clientY);
            Gizmos.DrawRay(ray.origin, ray.direction, 0xff0000, 10);
        }
    });

    //@ts-ignore
    window.addEventListener("touchmove", e => {
        console.log("touchmove");
    })

    //@ts-ignore
    window.addEventListener("touchend", evt => {
        console.log("touchend");
        this.unTouched();
    });
```

**Comment by ROBYER1** [comment] 2022-11-28 16:01
I also tried using `document.addEventListener` for touchstart and had the same issue. Interestingly I see this error every time I touch the screen in AR using the sample project in Mozilla WebXR Viewer

```
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values. {"isBufferGeometry": true, "uuid": "2195d14d-c053-41b1-b5ee-83c33045a4e2", "name": "", "type": "BufferGeometry", "index": null, "attributes": {"position": {"isBufferAttribute": true, "name": "", "array": {"0": 0.25999999046325684, "1": 0.5799999833106995, "2": -0.8799999952316284, "3": -342906080, "4": -306271072, "5": 888039104}, "itemSize": 3, "count": 2, "normalized": false, "usage": 35044, "updateRange": {"offset": 0, "count": -1}, "version": 2}}, "morphAttributes": {}, "morphTargetsRelative": false, "groups": [], "boundingBox": null, "boundingSphere": {"center": {"x": -0.19560186564922333, "y": 0.2725563049316406, "z": 0.4073042571544647}, "radius": NaN}, "drawRange": {"start": 0, "count": Infinity}, "userData": {}, "_listeners": {"dispose": [onGeometryDispose()]}}
```

**Comment by ROBYER1** [comment] 2022-11-29 15:57
I got touch events registering on iOS using `window.addEventListener` on its own, however I am finding that screenPointToRay is causing the error above only on iOS WebXR Viewer in AR

 ```public screenPointToRay(x: number, y: number, ray?: THREE.Ray): THREE.Ray {
    const origin = this._origin;
    origin.set(x, y, -1);
    this.context.input.convertScreenspaceToRaycastSpace(origin);
    origin.z = -1;
    origin.unproject(this.context.mainCamera);

    const dir = this._direction.set(origin.x, origin.y, origin.z);
    const camPosition = getWorldPosition(this.context.mainCamera);
    dir.sub(camPosition);
    dir.normalize();
    if (ray) {
        ray.set(camPosition, dir);
        return ray;
    }
    else {
        return new THREE.Ray(camPosition.clone(), dir.clone());
    }
}```

**Comment by marwie** [comment] 2022-11-29 16:14
The shared code sample is not part of the core - could you verify that you get the same error when using the method on the camera component ?

**Comment by ROBYER1** [comment] 2022-11-29 16:22
I dug further into this, I found that `this.context.domWidth` returns 0 in iOS WebXR viewer only in AR

```
convertScreenspaceToRaycastSpace(vec2: Vec2) {
    console.log("this.context.domX: ", this.context.domX);
    console.log("this.context.domWidth: ", this.context.domWidth);
    vec2.x = (vec2.x - this.context.domX) / this.context.domWidth * 2 - 1;
    vec2.y = -((vec2.y - this.context.domY) / this.context.domHeight) * 2 + 1;
}
```

**Comment by ROBYER1** [comment] 2022-11-29 16:29
Okay, I found the cause!

`this.context.input.convertScreenspaceToRaycastSpace(origin)` on iOS WebXR Viewer returns '0' for `this.context.domWidth` and `this.context.domHeight`.

Changing those to `window.innerWidth` and `window.innerHeight` works correct for WebXR AR with Mozilla WebXR Viewer on iOS

Sample code where I made those methods local functions for testing (sorry for any mess, I spent actual days scratching my head over this!):

```

start()
{
    WebXR.addEventListener(WebXREvent.XRStarted, this.onXRStarted.bind(this));
    
    window.addEventListener("touchstart", e => {
        console.log("touchstart", e);
        this.startCoroutine(this.showThenHideTouchCube(), FrameEvent.Update);
        for (let i = 0; i < e.changedTouches.length; i++) {
            const touch = e.changedTouches[i];
            const mainCam = getComponent(this.context.mainCamera, Camera);
            console.log("touch client x: ",touch.clientX);
            console.log("touch client y: ", touch.clientY);
            //const ray = mainCam.screenPointToRay(touch.clientX, touch.clientY);
            const ray = this.screenPointToRay(touch.clientX, touch.clientY);
            Gizmos.DrawRay(ray.origin, ray.direction, 0xff0000, 10);
        }
    });
   
    //@ts-ignore
    window.addEventListener("touchmove", e => {
        console.log("touchmove");
        GameObject.setActive(this.object2, true);
    });

    //@ts-ignore
    window.addEventListener("touchend", evt => {
        console.log("touchend");
        this.unTouched();
    });
}

public screenPointToRay(x: number, y: number, ray?: THREE.Ray): THREE.Ray {
    console.log("x: ", x, "y: ", y);
    console.log("this._origin: ", this._origin);
    //const origin = this._origin;
    const origin = new THREE.Vector3(x,y,-1);
    
    console.log("main camera origin: ", this.context.mainCamera.position);
    //origin.set(x, y, -1);
    console.log("origin x: ", origin.x);

    this.convertScreenspaceToRaycastSpace(origin);
    //this.context.input.convertScreenspaceToRaycastSpace(origin);
    //origin.z = -1;
    console.log("origin x: ", origin.x);
    origin.unproject(this.context.mainCamera);

    const dir = this._direction.set(origin.x, origin.y, origin.z);
    console.log("dir: ",dir);
    const camPosition = getWorldPosition(this.context.mainCamera);
    console.log("camPosition: ", camPosition);
    dir.sub(camPosition);
    dir.normalize();
    if (ray) {
        ray.set(camPosition, dir);
        return ray;
    }
    else {
        return new THREE.Ray(camPosition.clone(), dir.clone());
    }
}

convertScreenspaceToRaycastSpace(vec2: Vec2) {
    console.log(this);
    console.log("this.context.domX: ", this.context.domX);
    console.log("this.context.domWidth: ", this.context.domWidth);
    console.log(window.innerWidth);
    vec2.x = (vec2.x - this.context.domX) / window.innerWidth * 2 - 1;
    vec2.y = -((vec2.y - this.context.domY) / window.innerHeight) * 2 + 1;
}

public touched()
{
 console.log("touched");
 //this.setTargetFromRaycast();
}

public unTouched()
{
 console.log("unTouched");
 //this.clearTarget();
}

**Comment by ROBYER1** [comment] 2022-11-30 11:37
It seems to be this line in engine_input.ts that needs to be changed:
```
    convertScreenspaceToRaycastSpace(vec2: Vec2) {
        vec2.x = (vec2.x - this.context.domX) / this.context.domWidth * 2 - 1;
        vec2.y = -((vec2.y - this.context.domY) / this.context.domHeight) * 2 + 1;
    }
```
to:
```
    convertScreenspaceToRaycastSpace(vec2: Vec2) {
    vec2.x = (vec2.x - this.context.domX) / window.innerWidth * 2 - 1;
    vec2.y = -((vec2.y - this.context.domY) / window.innerHeight) * 2 + 1;
    }
```

**Comment by marwie** [comment] 2022-11-30 17:21
could you try if 2.51.0-pre fixes the issue?

**Comment by ROBYER1** [comment] 2022-12-07 13:47
@marwie 2.51.0-pre breaks this for me, I have a small repro project here. On 2.50.0-pre it works fine in Mozilla WebXR to drag around the plant pot while in AR. In 2.51.0-pre, screenPointToRay fires from some random location and doesn't seem to move the draggable around.

See line 341/342 of ARControls.ts in this example where you can see my local use of `const ray = this.screenPointToRay(touch.clientX, touch.clientY);` works fine with 2.50.0-pre but not with 2.51.0-pre. Interestingly when using line 342 instead of 341 with `const ray = this.context.mainCameraComponent!.screenPointToRay(touch.clientX, touch.clientY);`, the dragging still doesn't work in AR.
[ARDemo-221207_uw.zip](https://github.com/needle-tools/needle-engine-support/files/10176616/ARDemo-221207_uw.zip)

**Comment by marwie** [comment] 2022-12-07 14:06
@ROBYER1

- are you using a custom version of screenPointToRay? 
- is it not working when in XR or not working before that already?

**Comment by marwie** [comment] 2022-12-07 14:13
Thanks - I look into it!

**Closed** 2022-12-09 22:33 UTC
Labels: fixed → to verify
