### ISSUE TITLE
UI Button events no longer fire in 2.13.1-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#31] opened 2022-09-01 09:59 UTC
Since updating, buttons in a worldspace UI canvas no longer animate or fire their events

**Comment by marwie** [comment] 2022-09-01 10:19
Just tried in that version and works here - could you provide a little more info?

**Comment by ROBYER1** [comment] 2022-09-01 10:50
> Just tried in that version and works here - could you provide a little more info?

I'll send you a repro project

**Comment by marwie** [comment] 2022-09-01 16:13
Caused by cross-glb referrence resolving breaking for EventLists. Should be fixed in ``2.14.1-pre``

**Closed** 2022-09-01 16:14 UTC
