### ISSUE TITLE
OnEnable and OnDisable don't fire on scripts turned on/off by animation

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#74] opened 2022-09-28 10:23 UTC
Using Unity 2022.1.16f1, Exporter 2.26.0-pre

Make a scene with an animation on something - add Rotate.ts from the example docs and make the animation enable/disable it - sample code below. You will see that if the script is disabled by default then turned on by animation, it springs into life but disabling it via animation doesn't work. OnEnable/OnDisable don't fire during this either.

```cs
import { Behaviour } from "@needle-tools/engine/engine-components/Component";

export class Rotate extends Behaviour
{
    speed : number = 1;
    isX: boolean = false;
    isZ: boolean = false;

    OnEnable()
    {
        console.log("enabled");
    }

    OnDisable()
    {
        console.log("disabled");
    }

    update(){
        if(this.isX == true)
        {
            this.gameObject.rotateX(this.context.time.deltaTime * this.speed);
        }
        else
        {
            if(this.isZ == true)
            {
                this.gameObject.rotateZ(this.context.time.deltaTime * this.speed);
            }
            else
            {
                this.gameObject.rotateY(this.context.time.deltaTime * this.speed);
            }
        }
    }
}
```

**Comment by marwie** [comment] 2022-09-28 12:25
One reason for OnEnabe and OnDisable not firering might be that they are defined like ``onEnable`` and ``onDisable``

**Comment by ROBYER1** [comment] 2022-09-29 15:15
> One reason for OnEnabe and OnDisable not firering might be that they are defined like `onEnable` and `onDisable`

OnEnable and OnDisable seem to be the correct way to define them (at least for the inspector to have a tickbox to enable/disable the script)

The main issue here is that when disabled via animation, the Update loop continues regardless of the script/its gameobject being inactive.

**Comment by marwie** [comment] 2022-09-29 23:37
Thanks for reporting. The issue was caused by the animation setting float values instead of booleans which was not handled - will be fixed in the next update

**Closed** 2022-10-05 16:30 UTC
Labels: fixed
