### ISSUE TITLE
UI Text: Empty textboxes when switchting out text with rich text <tags> via script

### ISSUE THREAD

**Issue by Podden** [needle-tools/needle-engine-support#168] opened 2023-07-20 14:29 UTC
### Describe the bug 💬

I noticed that I sometimes get empty text boxes, When I'm switching out text on a text component which has <b> tags in it with another one which hasn't.

### Operating System 👩‍💻

Windows

### Editor Version 🎲

2022.x

### Needle Exporter version

3.10.2

### Steps to reproduce 🔢

```bash
1. Creating a Script with two strings which switches out text in text components, eg:
 private textfield: Text | null = null;
 public setText(language: string) {
        if (!this.textfield) {
            this.textfield = GameObject.getComponent(this.gameObject, Text);
        }
        if (this.textfield) {
            if (language === "de")
                this.textfield.text = this.textDE;
            else if (language === "en")
                this.textfield.text = this.textEN;
            else if (language === "nl")
                this.textfield.text = this.textNL;
        }
    }
2. Filling the Strings in the Editor with text with and without rich text tags
3. Switching between them in the build
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment] 2023-07-20 14:49
Hi, thanks for the report. Reproduced the issue here

**Comment by marwie** [comment] 2023-07-20 15:00
Should be fixed in the next update

https://github.com/needle-tools/needle-engine-support/assets/5083203/9d76eaa0-6e58-461e-88eb-2d0d17270bdf

**Comment by marwie** [comment] 2023-09-03 12:24
closing due to inactivity

**Closed by marwie** 2023-09-03 12:24 UTC
Labels: bug, fixed → to verify
